name: Github Pages CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # - name: Install and Build 🔧
      #   run: |
      #     npm ci
      #     npm run build

      - name: Deploy with rebase to gh-pages 🚀
        run: |
          # Set Git identity globally to avoid re-configuring in clone
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone --depth=1 --branch=gh-pages https://x-access-token:${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.CI_REPOSITORY_NAME }} gh-pages-temp
          cd gh-pages-temp

          git remote add upstream https://x-access-token:${{ secrets.CI_PERSONAL_ACCESS_TOKEN }}@github.com/${{ secrets.CI_REPOSITORY_NAME }}
          git fetch upstream main
          git rebase upstream/main || echo "⚠️ Rebase had conflicts and was skipped"

          rm -rf portfolio
          mkdir -p portfolio
          cp -r ../src/* portfolio/
          cp -r ../index.html portfolio/

          git add .
          git commit -m "Deploy via GitHub Actions 🚀" || echo "Nothing to commit"
          git push origin gh-pages --force
